sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl 
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-306610 #Setting applied in gclouc cli
  - gcloud config set compute/zone europe-west1-b #Setting applied in gclouc cli
  - gcloud container clusters get-credentials cluster-1 #Setting applied in gclouc cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME"  --password-stdin
  - docker build -t reaaavaaahhh/react-test -f ./client/Dockerfile.dev ./client
# kubectl create secret generic pgpassword --from-literal PGPASSWORD=pgpassword
#    curl -LO https://git.io/get_helm.sh
#    chmod 700 get_helm.sh
#    ./get_helm.sh    
# Do not forget to install helm with tiller and ingress on cluster with gcloud cli
# kubectl create serviceaccount --namespace kube-system tiller
# kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
# helm init --service-account tiller --upgrade
# helm install stable/nginx-ingress --name my-nginx --set rbac.create=true
script:
  - docker run -e CI=true reaaavaaahhh/react-test npm test -- --coverage


deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
  on:
    branch: master
